#!/usr/bin/env bash

service=$1
secrets=$2
if [ -z "$service" ] || [ -z "$secrets" ]
then
      echo "usage: $0 <service> <secrets_directory>"
	  exit 1
fi

kmsKeyName="secretskey"

#kmsKeyArn=$(aws kms describe-key --key-id alias/${kmsKeyName} --query 'KeyMetadata.Arn' --output text)
secretSharingPolicy=$(cat <<EOF
{
  "Version" : "2012-10-17",
  "Statement" : [
    {
      "Effect" : "Allow",
      "Principal" : {
        "AWS" : "ROLE_ARN"
      },
      "Action" : "secretsmanager:GetSecretValue",
      "Resource" : "*",
      "Condition" : {
        "ForAnyValue:StringEquals" : {
          "secretsmanager:VersionStage" : "AWSCURRENT"
        }
      }
    }
  ]
}
EOF
)


for secret in $(ls ${secrets})
do
  secretkey=$service-$secret
  jsonlint -q ${secrets}/${secret}
	aws secretsmanager put-secret-value --secret-id ${secretkey%.json} \
		--secret-string file://${secrets}/${secret}

done

exit 0