#!/usr/bin/env bash
service=$1
secrets=$2
if [ -z "$service" ] || [ -z "$secrets" ]
then
        echo "usage: $0 <service> <secrets_directory>"
    exit 1
fi

kmsKeyName="secretskey"
export AWS_DEFAULT_REGION=us-east-1

secretSharingPolicy=$(cat <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "ROLE_ARN"
            },
            "Action": "secretsmanager:GetSecretValue",
            "Resource": "*",
            "Condition": {
                "ForAnyValue:StringsEquals" : {
                    "secretmanager:VersionStage" : "AWSCURRENT"
                }
            }
        }
    ]
}
EOF
)

for secret in $(ls "${secrets}")
do
    secretkey=$service-$secret

aws secretsmanager create-secret --name "${secretkey%.json}" --description "Credentials for ${secretkey%.json}" --secret-string file://"${secrets}"/"${secret}"

done

exit 0