apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  labels:
    type: prometheus-server
spec:
  storageClassName: standard
  capacity:
    storage: STORAGESIZEGi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
  name: prometheus-pvc
  namespace: NAMESPACE
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: STORAGESIZEGi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate