apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.0.3
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: SERVICE_NAME-admin
              key: admin-user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: SERVICE_NAME-admin
              key: admin-password
        - name: GF_SECURITY_LOKI_USER
          valueFrom:
            secretKeyRef:
              name: SERVICE_NAME-user
              key: loki-user
        - name: GF_SECURITY_LOKI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: SERVICE_NAME-user
              key: loki-password
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests: 
            memory: 500M
            cpu: "500m"
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources